//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MY_PROJECT.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande_FOURNISSEUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commande_FOURNISSEUR()
        {
            this.DETAIL_CMD_FOURNISS = new HashSet<DETAIL_CMD_FOURNISS>();
        }
    
        public int ID_CMD_FRNS { get; set; }
        public Nullable<int> ID_FOURNISS { get; set; }
        public Nullable<System.DateTime> DATE_CMD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_CMD_FOURNISS> DETAIL_CMD_FOURNISS { get; set; }
        public virtual Fournisseur Fournisseur { get; set; }
    }
}
