//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MY_PROJECT.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fournisseur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fournisseur()
        {
            this.Commande_FOURNISSEUR = new HashSet<Commande_FOURNISSEUR>();
        }
    
        public int id_Fournisseur { get; set; }
        public string Nom_Fourniss { get; set; }
        public string adresse_fournisseur { get; set; }
        public string email_Fournisseur { get; set; }
        public string pays { get; set; }
        public string telephone_Fournisseur { get; set; }
        public string CIN_Fournisseur { get; set; }
        public byte[] image_Fournisseur { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commande_FOURNISSEUR> Commande_FOURNISSEUR { get; set; }
    }
}
