//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MY_PROJECT.Entity_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GEST_VENTE_Entities : DbContext
    {
        public GEST_VENTE_Entities()
            : base("name=GEST_VENTE_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorie> Categories { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Commande_Client> Commande_Client { get; set; }
        public virtual DbSet<Commande_FOURNISSEUR> Commande_FOURNISSEUR { get; set; }
        public virtual DbSet<DETAIL_CMD_CLIENT> DETAIL_CMD_CLIENT { get; set; }
        public virtual DbSet<DETAIL_CMD_FOURNISS> DETAIL_CMD_FOURNISS { get; set; }
        public virtual DbSet<Fournisseur> Fournisseurs { get; set; }
        public virtual DbSet<Loginn> Loginns { get; set; }
        public virtual DbSet<Produit> Produits { get; set; }
    }
}
