//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MY_PROJECT.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produit()
        {
            this.DETAIL_CMD_CLIENT = new HashSet<DETAIL_CMD_CLIENT>();
            this.DETAIL_CMD_FOURNISS = new HashSet<DETAIL_CMD_FOURNISS>();
        }
    
        public int id_Produit { get; set; }
        public string Nom_Produit { get; set; }
        public decimal Prix_achat { get; set; }
        public decimal Prix_vent { get; set; }
        public Nullable<double> Quantite_Produit_stock { get; set; }
        public Nullable<int> id_catégorie { get; set; }
        public byte[] Photo_produit { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_CMD_CLIENT> DETAIL_CMD_CLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_CMD_FOURNISS> DETAIL_CMD_FOURNISS { get; set; }
    }
}
